### PR TITLE
RDY: Add content to documentation

### PR DESCRIPTION
**Pull request by AngelNull**
This PR is to get some initial ground down on the documentation for future building as right now there isn't a lot here, also another note is that my commits will be chunked together from now on to create less spam - just wanted to get the initial build ready for the draft PR.  

### Notes 

- Documentation pages (as of current) can be found in `/docs/` apart from the index and 404 pages, which are in the root of the repository. 
- A lot of pages will contain filler content as of now, assistance is needed in filling in these pages with accurate information.
- A build of the PR docs can be found at https://angelnull.github.io/beemo-docs

### Checklist

- [x] Landing Page

Moderation:
- [x] Archives
- [x] Banpools
- [x] Preset-Reasons

Utility:
- [x] XP
- [x] Honey

### CODE REVIEW

**Comment by AngelNull** [comment]
Content additions may not be very lengthy, some content filling needs to be in places like `archives` and `honey` but since I know less about the internals of these features I'll allow you to do a lot of the filling. This PR should work for a good amount of base content, although links on beemo.gg/subscribe may need updating to reflect the directory layout.

**Comment by AyuAi** [comment]
Firstly, I want to say that I super appreciate the time you have put into giving this a framework c: While it isn't exactly how I envisioned the docs to be, it is something that I will definitely utilize as a starting point as long as you are okay with me modifying your PR 👀

**Review by AyuAi — CHANGES_REQUESTED** [review]
I noticed you added GPL 3.0 as a license for the repository. Not that it matters a ton since it is a docs repo, but I was thinking of MIT instead, as it is much simpler. Is there a particular reason you chose GPL 3.0?

**Comment by AngelNull** [comment]
> I noticed you added GPL 3.0 as a license for the repository. Not that it matters a ton since it is a docs repo, but I was thinking of MIT instead, as it is much simpler. Is there a particular reason you chose GPL 3.0?

Out of habit I threw a license in when I saw there wasn't one, and I just used whatever you had in another repository. Feel free to remove, I just always put licenses cause my brain goes on autopilot. I can update to MIT if wanted. It's just for users who fork the repo etc.

**Comment by AyuAi** [comment]
Heyo @AngelNull !

Thanks again for the PR :) It has been a useful baseline for docs, even though it is missing a little bit; I think it would be useful to merge and use!

I have created a PR for your docs main branch. If you merge that PR, I will merge this PR into the official docs (https://github.com/AngelNull/beemo-docs/pull/1)

Also, sorry it has taken a while 🙏 Mix of motivation and prioritizations have held things up for a bit.

**Review by AyuAi — APPROVED** [review]

**Pull request merged**
